"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-10-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sentinelai.models.database  # noqa: F401  (UTCDateTime custom type)


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=200), nullable=False),
    sa.Column('customer_name', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('origin_country', sa.String(length=3), nullable=True),
    sa.Column('destination_country', sa.String(length=3), nullable=True),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=False),
    sa.Column('report_required', sa.Boolean(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_analyses_level_score', ['risk_level', 'risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_request_hash'), ['request_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_risk_score'), ['risk_score'], unique=False)

    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('timestamp', sentinelai.models.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('ref', sa.String(length=100), nullable=True),
    sa.Column('edge_key', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_key')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_timestamp'), ['timestamp'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('sar_filed', sa.Boolean(), nullable=False),
    sa.Column('sar_reference', sa.String(length=100), nullable=True),
    sa.Column('sar_filed_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_deadline', sentinelai.models.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('report_deadline', sentinelai.models.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('signal_codes', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('case_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sentinelai.models.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_comments_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_comments_case_id'))

    op.drop_table('case_comments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_case_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_cases_case_number'))
        batch_op.drop_index(batch_op.f('ix_cases_assigned_to'))

    op.drop_table('cases')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_timestamp'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_target'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_source'))

    op.drop_table('graph_edges')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_log')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_risk_score'))
        batch_op.drop_index(batch_op.f('ix_analyses_risk_level'))
        batch_op.drop_index(batch_op.f('ix_analyses_request_hash'))
        batch_op.drop_index('ix_analyses_level_score')
        batch_op.drop_index(batch_op.f('ix_analyses_customer_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
