#!/usr/bin/env python
"""Rebuild the GitHub-Pages copy in docs/ from frontend/ (single source of truth).

    python scripts/sync_docs.py            # write docs/
    python scripts/sync_docs.py --check    # exit 1 if docs/ is stale (used in CI)

docs/ gets the identical index.html/app.js/styles.css; only docs/config.js differs - it points
the static site at the hosted API (override with SENTINEL_PAGES_API).
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC, DST = ROOT / "frontend", ROOT / "docs"
SHARED = ("index.html", "app.js", "styles.css")
API = os.environ.get("SENTINEL_PAGES_API", "https://sentinelai-api.onrender.com")
CONFIG = (
    "// Generated by scripts/sync_docs.py - the static site talks to the hosted API.\n"
    f'window.SENTINEL_CONFIG = {{ apiBase: "{API}" }};\n'
)


def main(check: bool) -> int:
    expected = {name: (SRC / name).read_bytes() for name in SHARED}
    expected["config.js"] = CONFIG.encode()
    stale = [n for n, data in expected.items() if not (DST / n).exists() or (DST / n).read_bytes() != data]
    if check:
        if stale:
            print("docs/ is out of sync with frontend/: " + ", ".join(stale) + "  -> run `make docs-sync`")
            return 1
        print("docs/ is in sync")
        return 0
    DST.mkdir(exist_ok=True)
    for name, data in expected.items():
        (DST / name).write_bytes(data)
    print("Synced: " + ", ".join(expected))
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
